Chapter06/JinjiSystem-master/config/routes.rb
Rails.application.routes.draw do
  resources :shains do
    member do
      get 'standup'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Chapter06/JinjiSystem-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Chapter06/JinjiSystem-master/app/models/bucho.rb
class Bucho < Shain
  def yakushoku
    '部長'
  end

  def standup
    '部長は起立しました'
  end

  def salary
    kihonkyu * 3
  end
end

Chapter06/JinjiSystem-master/app/models/shain.rb
class Shain < ApplicationRecord
end

Chapter06/JinjiSystem-master/app/models/shunin.rb
class Shunin < Shain
  def yakushoku
    '主任'
  end

  def standup
    '主任は慌てて起立しました'
  end

  def salary
    kihonkyu * 2 + 1000
  end
end

Chapter06/JinjiSystem-master/app/models/tanto.rb
class Tanto < Shain
  def yakushoku
    '担当'
  end

  def standup
    '担当は慌てて起立しました'
  end

  def salary
    kihonkyu
  end
end

Chapter06/JinjiSystem-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Chapter06/JinjiSystem-master/app/controllers/shains_controller.rb
class ShainsController < ApplicationController
  before_action :set_shain, only: [:show, :edit, :update, :destroy, :standup]

  # GET /shains
  # GET /shains.json
  def index
    @shains = Shain.all
  end

  # GET /shains/1
  # GET /shains/1.json
  def show
  end

  # GET /shains/new
  def new
    @shain = Shain.new
  end

  # GET /shains/1/edit
  def edit
  end

  # POST /shains
  # POST /shains.json
  def create
    @shain = Shain.new(shain_params)

    respond_to do |format|
      if @shain.save
        format.html { redirect_to @shain.becomes(Shain), notice: 'Shain was successfully created.' }
        format.json { render :show, status: :created, location: @shain }
      else
        format.html { render :new }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shains/1
  # PATCH/PUT /shains/1.json
  def update
    respond_to do |format|
      if @shain.update(shain_params)
        format.html { redirect_to @shain.becomes(Shain), notice: 'Shain was successfully updated.' }
        format.json { render :show, status: :ok, location: @shain }
      else
        format.html { render :edit }
        format.json { render json: @shain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shains/1
  # DELETE /shains/1.json
  def destroy
    @shain.destroy
    respond_to do |format|
      format.html { redirect_to shains_url, notice: 'Shain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def standup
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shain
      @shain = Shain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shain_params
      params.require(:shain).permit(:name, :type, :kihonkyu)
    end
end

Chapter06/JinjiSystem-master/app/helpers/application_helper.rb
module ApplicationHelper
end

Chapter06/JinjiSystem-master/app/helpers/shains_helper.rb
module ShainsHelper
end

Chapter06/JinjiSystem-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JinjiSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Chapter06/JinjiSystem-master/app/views/shains/_form.html.erb
<%= form_with(model: shain.becomes(Shain), local: true) do |form| %>
  <% if shain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shain.errors.count, "error") %> prohibited this shain from being saved:</h2>

      <ul>
      <% shain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :shain_name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, ['Tanto', 'Shunin', 'Bucho'], id: :shain_yakushoku %>
  </div>

  <div class="field">
    <%= form.label :kihonkyu %>
    <%= form.number_field :kihonkyu, id: :shain_kihonkyu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Chapter06/JinjiSystem-master/app/views/shains/edit.html.erb
<h1>Editing Shain</h1>

<%= render 'form', shain: @shain %>

<%= link_to 'Show', @shain.becomes(Shain) %> |
<%= link_to 'Back', shains_path %>

Chapter06/JinjiSystem-master/app/views/shains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>社員一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>役職</th>
      <th>基本給</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shains.each do |shain| %>
      <tr>
        <td><%= shain.name %></td>
        <td><%= shain.yakushoku %></td>
        <td><%= shain.kihonkyu %></td>
        <td><%= link_to 'Show', shain.becomes(Shain) %></td>
        <td><%= link_to 'Edit', edit_shain_path(shain) %></td>
        <td><%= link_to 'Destroy', shain.becomes(Shain), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shain', new_shain_path %>

Chapter06/JinjiSystem-master/app/views/shains/new.html.erb
<h1>New Shain</h1>

<%= render 'form', shain: @shain %>

<%= link_to 'Back', shains_path %>

Chapter06/JinjiSystem-master/app/views/shains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @shain.name %>
</p>

<p>
  <strong>役職:</strong>
  <%= @shain.yakushoku %>
</p>

<p>
  <strong>基本給:</strong>
  <%= @shain.kihonkyu %>
</p>

<p>
  <strong>給与:</strong>
  <%= @shain.salary %>
</p>

<p>
    <%= link_to '起立を号令', standup_shain_path %>
</p>
<%= link_to 'Edit', edit_shain_path(@shain) %> |
<%= link_to 'Back', shains_path %>

Chapter06/JinjiSystem-master/app/views/shains/standup.html.erb
<h2><%= @shain.standup %></h2>